name: Deploy Terraform Resources on AWS

on:
  push:
    branches:
      - main
    paths:
      - tf-acm-cert/**
  pull_request:
    branches:
      - main
    paths:
      - tf-acm-cert/**

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'
      
      - name: Debug AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"


      - name: AWS Credentials Setup
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init and Plan
        working-directory: ./tf-acm-cert
        run: make verify

      - name: Apply Terraform
        if: ${{ github.ref == 'refs/heads/main' }}
        working-directory: ./tf-acm-cert
        run: make deploy
